// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConditionDeviseController from "./condition_devise_controller"
application.register("condition-devise", ConditionDeviseController)

import FormByPlayerController from "./form_by_player_controller"
application.register("form-by-player", FormByPlayerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import UsernameAutocompleteController from "./username_autocomplete_controller"
application.register("username-autocomplete", UsernameAutocompleteController)
